//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: message.proto
namespace MessageLib
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"Message")]
  public partial class Message : global::ProtoBuf.IExtensible
  {
    public Message() { }

    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _from;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"from", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string From
    {
      get { return _from; }
      set { _from = value; }
    }
    private string _body;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name = @"body", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Body
    {
      get { return _body; }
      set { _body = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
    { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
}