### Generated by rprotoc. DO NOT EDIT!
### <proto file: message.proto>
# message Message{
#   required int32 id = 1;
#   required string from = 2;
#   required string body = 3;
# }
require 'protobuf/message/message'
require 'protobuf/message/enum'
require 'protobuf/message/service'
require 'protobuf/message/extend'

class Message < ::Protobuf::Message
  defined_in __FILE__
  required :int32, :id, 1
  required :string, :from, 2
  required :string, :body, 3
end